#point these to absolute paths
CHARM_DIR = $(HOME)/Install/charm
BASE_DIR = $(HOME)/Projects/Charap/Charap

#common options
CHARMC = $(CHARM_DIR)/bin/charmc -DUSE_ESSL_WRAPPER=0
OPTS	= -std=c++17 -g
LD_OPTS = 

INCS = -I${BASE_DIR}
